/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module externalfsm_4 (
    input clk,
    input rst,
    input [2:0] buttonsignal,
    output reg lightshit
  );
  
  
  
  wire [1-1:0] M_slowclock_value;
  counter_7 slowclock (
    .clk(clk),
    .rst(rst),
    .value(M_slowclock_value)
  );
  
  
  localparam STATEGAMESTART_state = 3'd0;
  localparam Q1DISPLAY_state = 3'd1;
  localparam HPDECREASE1A_state = 3'd2;
  localparam HPDECREASE1B_state = 3'd3;
  localparam GAMEOVER_state = 3'd4;
  
  reg [2:0] M_state_d, M_state_q = STATEGAMESTART_state;
  
  always @* begin
    M_state_d = M_state_q;
    
    lightshit = 1'h0;
    
    case (M_state_q)
      STATEGAMESTART_state: begin
        lightshit = 1'h0;
        if (buttonsignal == 3'h1) begin
          M_state_d = Q1DISPLAY_state;
        end
      end
      Q1DISPLAY_state: begin
        lightshit = 1'h1;
        M_state_d = Q1DISPLAY_state;
      end
    endcase
  end
  
  always @(posedge M_slowclock_value) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h0;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
endmodule
