/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module modulo1_2 (
    input a,
    input b,
    output reg out
  );
  
  
  
  always @* begin
    if (a == 1'h0) begin
      out = 1'h0;
    end else begin
      if (a == 1'h1) begin
        if (b == 1'h1) begin
          out = 1'h0;
        end else begin
          out = 1'h1;
        end
      end else begin
        if (a == 2'h2) begin
          if (b == 1'h1 || b == 2'h2) begin
            out = 1'h0;
          end else begin
            out = 1'h1;
          end
        end else begin
          if (a == 2'h3) begin
            if (b == 1'h1 || b == 2'h3) begin
              out = 1'h0;
            end else begin
              out = 1'h1;
            end
          end else begin
            if (a == 3'h4) begin
              if (b == 1'h1 || b == 2'h2 || b == 3'h4) begin
                out = 1'h0;
              end else begin
                out = 1'h1;
              end
            end else begin
              if (a == 3'h5) begin
                if (b == 1'h1 || b == 3'h5) begin
                  out = 1'h0;
                end else begin
                  out = 1'h1;
                end
              end else begin
                if (a == 3'h6) begin
                  if (b == 1'h1 || b == 2'h2 || b == 2'h3 || b == 3'h6) begin
                    out = 1'h0;
                  end else begin
                    out = 1'h1;
                  end
                end else begin
                  if (a == 3'h7) begin
                    if (b == 1'h1 || b == 3'h7) begin
                      out = 1'h0;
                    end else begin
                      out = 1'h1;
                    end
                  end else begin
                    if (a == 4'h8) begin
                      if (b == 1'h1 || b == 2'h2 || b == 3'h4 || b == 4'h8) begin
                        out = 1'h0;
                      end else begin
                        out = 1'h1;
                      end
                    end else begin
                      if (a == 4'h9) begin
                        if (b == 1'h1 || b == 2'h3 || b == 4'h9) begin
                          out = 1'h0;
                        end else begin
                          out = 1'h1;
                        end
                      end else begin
                        out = 1'h1;
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end
    end
  end
endmodule
