/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_10 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] out
  );
  
  
  
  reg [15:0] expr;
  
  always @* begin
    out = 1'h0;
    expr = $signed(a);
    if ({alufn[1+0-:1], alufn[0+0-:1]} == 2'h0) begin
      out = expr << b;
    end
    if ({alufn[1+0-:1], alufn[0+0-:1]} == 2'h1) begin
      out = expr >> b;
    end
    if ({alufn[1+0-:1], alufn[0+0-:1]} == 2'h2) begin
      out = expr <<< b;
    end
    if ({alufn[1+0-:1], alufn[0+0-:1]} == 2'h3) begin
      out = expr >>> b;
    end
  end
endmodule
